version: "2"

services:
  consul: 
    image: consul:0.8.3
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net 
  
  go-micro-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: johnantonusmaximus/server-new:latest
    environment:
    - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul 
    networks:
      - sky-net

  go-micro-client:
    build:
      context: .
      dockerfile: client/Dockerfile 
    image: johnantonusmaximus/micro-client:latest 
    environment:
    - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul 
      - go-micro-server 
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge